import "@/styles/globals.css";
import React from "react";

export const metadata = {
  title: "Chat Gpt",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div>
          {/* SideBar  */}
          {/* ClientProvider  */}
          <div className="bg-[#343541]  flex-1">{children}</div>
        </div>
      </body>
    </html>
  );
}
